### ISSUE TITLE
Allow multiple anaconda versions to be installed

### ISSUE THREAD

**Issue by bilsch** [andrewrothstein/ansible-anaconda#21]
It would be nice to have the link be optional. In my case I need both anaconda2 and 3 to be installed / maintained.

```
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: true
  vars:
    python_versions:
      - 2
      - 3
(...)
  tasks:
(...)
    - name: "Install anaconda for python versions"
      with_items: "{{ python_versions }}"
      loop_control:
        loop_var: version
      include_role:
        name: andrewrothstein.anaconda
      vars:
        anaconda_parent_dir: /hadoop/anaconda
        anaconda_python_ver: "{{ version }}"
```

I can think of a few ways to tackle this - thoughts on what you would prefer? Simply making the [link](https://github.com/andrewrothstein/ansible-anaconda/blob/master/tasks/main.yml#L46) optional may work however I can see where you would want to have anaconda2 symlink to latest for 2, ditto for anaconda3.

Happy to submit a pr
